services:
  dev-container:
    image: thesis_image:develop
    build: .
    volumes:
      - /home/trukhinmaksim:/home/trukhinmaksim/Thesis/code/docker/container/src
    ports:
      - 8888:8888
      - 8000:8000
    tty: true                                                                                          
    stdin_open: true
