FROM python:3.11

USER root

WORKDIR /home/trukhinmaksim

#RUN pip install --no-cache-dir numpy==1.26.4
COPY requirements_readme.txt /home/trukhinmaksim

RUN pip install --no-cache-dir -r requirements_readme.txt

EXPOSE 8888
EXPOSE 8000

CMD ["/bin/bash"]
