FROM python:3.11

USER root

# Install basic dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git wget ca-certificates

# Add AMD ROCm repository (adjust for your desired ROCm version and Ubuntu version)
RUN wget https://repo.radeon.com/rocm/apt/debian/rocm.gpg.key && \
    apt-key add rocm.gpg.key && \
    sh -c 'echo "deb [arch=amd64] https://repo.radeon.com/rocm/apt/debian/ focal main" > /etc/apt/sources.list.d/rocm.list' && \
    apt-get update

# Install ROCm (install the full SDK for development)
RUN apt-get install -y rocm-hip-sdk numpy matplotlib scipy

# Install PyTorch with ROCm support (adjust version as needed)
RUN pip install torch --index-url https://download.pytorch.org/whl/rocm5.7

# Set working directory
WORKDIR /home/trukhinmaksim

COPY requirements.txt /home/trukhinmaksim
# Install any other Python dependencies
#RUN pip install --no-cache-dir -r requirements.txt
# Set the command to run your training script
CMD ["/bin/bash"]
